# Site settings
title: "Cache-Control:public, max-age=3155690000"
author: "Cache Hamm"
description: "This is where I like to publish my notes about software, projects I'm working on, and other things I'm thinking about."
keywords: "Software Engineering, Software Architecture, Node.js, Software Development"
biography: "Dad. Rider of bikes, rower of boats, brewer of coffee. Principal Engineer at <a href='http://www.shutterstock.com'>Shutterstock</a>."
colophon: "© 2015 — 2019 by Cache Hamm.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://cachecontrol.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "https://cachecontrol.github.io/"

twitter_username: cachecontrol
github_username: cachecontrol
linkedin_username: cachehamm
google-analytics: UA-142218054-1

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
